from ctbus_finance.importers.capitalone_credit_card import (
    Importer as CapitalOneCreditCardImporter,
)
from ctbus_finance.importers.capitalone_deposit_account import (
    Importer as CapitalOneDepositAccountImporter,
)
from ctbus_finance.importers.fidelity import Importer as FidelityImporter
from ctbus_finance.importers.health_equity import Importer as HealthEquityImporter
from ctbus_finance.importers.stock_action import BuyAction, SellAction
from ctbus_finance.importers.vanguard import Importer as VanguardImporter
from ctbus_finance.importers.venmo import Importer as VenmoImporter


account_patterns = [
    # Account
    ("Capital One Autopay", "Assets:Savings:CapitalOne"),
    ("Capital One Member Fee", "Expenses:Banking:CapitalOne:VentureX"),
    ("Mock Init Balance", "Income:Opening-Balances"),
    # Expenses
    ("GITHUB", "Expenses:Cloud-Services:Source-Hosting:Github"),
    ("DicksSportingGoods", "Expenses:Shopping:Sports:Dicks-Sporting-Goods"),
    ("Dicks Sporting Goods", "Expenses:Shopping:Sports:Dicks-Sporting-Goods"),
    ("Openai", "Expenses:Cloud-Services:AI:OpenAI"),
    ("Spotify", "Expenses:Entertainment:Music:Spotify"),
    ("Somervillema", "Expenses:Travel:Parking:Somerville"),
    ("Amazon Web Services", "Expenses:Cloud-Services:Amazon-Web-Services"),
    ("Amazon", "Expenses:Shopping:Amazon"),
    ("AMZN", "Expenses:Shopping:Amazon"),
    ("Prime Video", "Expenses:Entertainment:Video:Amazon-Prime-Video"),
    ("Mens Wearhouse", "Expenses:Shopping:Clothing:Mens-Warehouse"),
    ("Fsp\*boston Bouldering", "Expenses:Health:Fitness:Boston-Bouldering"),
    ("Mbta", "Expenses:Travel:Public-Transport:MBTA"),
    ("Geico", "Expenses:Travel:Insurance:Geico"),
    ("At \*Neaquarium", "Expenses:Entertainment:New-England-Aquarium"),
    ("New England Aquarium", "Expenses:Entertainment:New-England-Aquarium"),
    ("New Eng Aquarium", "Expenses:Entertainment:New-England-Aquarium"),
    ("eBay", "Expenses:Shopping:EBay"),
    ("Jellycat", "Expenses:Shopping:Toys:Jellycat"),
    ("Intuit \*Turbotax", "Expenses:Taxes:Software:TurboTax"),
    ("RMV", "Expenses:Travel:Registration:RMV"),
    ("Volo", "Expenses:Health:Sports:Volo"),
    ("Amtrak", "Expenses:Travel:Public-Transport:Amtrak"),
    ("E-Zpass", "Expenses:Travel:Tolls:E-Zpass"),
    ("Sq \*Antiquites Bolduc", "Expenses:Shopping:Collectibles:Les-Antiquities-Bolduc"),
    ("Citidental", "Expenses:Health:Dental:Citidental"),
    ("Costco \*Annual Renewal", "Expenses:Shopping:Memberships:Costco"),
    ("Costco", "Expenses:Shopping:Costco"),
    ("Pepita Coffee", "Expenses:Food:Coffee:Lamplighter"),
    ("Lamplighter Brew", "Expenses:Food:Coffee:Lamplighter"),
    ("Dunkin", "Expenses:Food:Coffee:Dunkin"),
    ("Club Cafe", "Expenses:Entertainment:Nightlife:Club-Cafe"),
    ("ZAPPOS.COM", "Expenses:Shopping:Clothing:Zappos"),
    ("Picante Taqueria", "Expenses:Food:Restaurants:Picante-Taqueria"),
    ("Jimsmarket", "Expenses:Food:Groceries:Jims-Market"),
    ("Exxon", "Expenses:Travel:Fuel:Exxon"),
    ("Howl at the Moon", "Expenses:Entertainment:Nightlife:Howl-at-the-Moon"),
    ("Frozen Hoagies", "Expenses:Food:Restaurants:Frozen-Hoagies"),
    ("Chipotle", "Expenses:Food:Restaurants:Chipotle"),
    ("Wholefds", "Expenses:Food:Groceries:Whole-Foods"),
    ("City of Somerville Flo", "Expenses:Travel:Parking:Somerville"),
    ("Druid", "Expenses:Food:Restaurants:Druid"),
    ("Caffe Nero", "Expenses:Food:Coffee:Caffe-Nero"),
    ("Shell Oil", "Expenses:Travel:Fuel:Shell"),
    ("d'AGOSTINOS", "Expenses:Food:Restaurants:DAgostinos"),
    ("d'AGOSTINO'S", "Expenses:Food:Restaurants:DAgostinos"),
    ("Nijiya Japanese", "Expenses:Food:Restaurants:Nijiya-Japanese"),
    ("El Jefes", "Expenses:Food:Restaurants:El-Jefes"),
    ("El Jefe's", "Expenses:Food:Restaurants:El-Jefes"),
    ("Felipes Taqueria", "Expenses:Food:Restaurants:Felipes-Taqueria"),
    ("Boston Sports Medicine", "Expenses:Health:Physiotherapy:Boston-Sports-Medicine"),
    ("Sunoco", "Expenses:Travel:Fuel:Sunoco"),
    ("Store", "Expenses:UNKNOWN"),
    ("Becky's Diner", "Expenses:Food:Restaurants:Beckys-Diner"),
    ("Trader Joe", "Expenses:Food:Groceries:Trader-Joes"),
    ("Moes", "Expenses:Food:Restaurants:Moes"),
    ("Moe's", "Expenses:Food:Restaurants:Moes"),
    ("Martys Corner Cafe", "Expenses:Food:Restaurants:Martys-Corner-Cafe"),
    ("Dollar General", "Expenses:Shopping:Groceries:Dollar-General"),
    ("Buzzys by Pass Gas", "Expenses:Travel:Fuel:Buzzys"),
    ("Carolicious", "Expenses:Food:Restaurants:Carolicious-Gourmet"),
    ("Toscanini's Ice Cream", "Expenses:Food:Ice-Cream:Toscaninis"),
    ("Mike & Patty's", "Expenses:Food:Restaurants:Mike-and-Pattys"),
    ("Remnant Brewing", "Expenses:Food:Coffee:Remnant"),
    ("Trattoria Il Panin", "Expenses:Food:Restaurants:Trattoria-Il-Panino"),
    ("Red Hen Baking Co", "Expenses:Food:Restaurants:Red-Hen-Baking-Co"),
    ("Speedway", "Expenses:Travel:Fuel:Speedway"),
    ("Starbucks", "Expenses:Food:Coffee:Starbucks"),
    ("Stewarts Shop", "Expenses:Travel:Fuel:Stewarts-Shop"),
    ("Subway", "Expenses:Food:Restaurants:Subway"),
    ("Insomnia Cookies", "Expenses:Food:Restaurants:Insomnia-Cookies"),
    ("Bom Dough", "Expenses:Food:Coffee:Bom-Dough"),
    ("Dairy Queen", "Expenses:Food:Restaurants:Dairy-Queen"),
    ("Ag Travel Plaza", "Expenses:Travel:Fuel:Ag-Travel-Plaza"),
    ("Katys Cafe", "Expenses:Food:Restaurants:Katys-Cafe"),
    ("McDonald's", "Expenses:Food:Restaurants:McDonalds"),
    ("Myway Bistro", "Expenses:Food:Restaurants:Myway-Bistro"),
    ("American Inn & Suites", "Expenses:Travel:Accommodation:American-Inn-and-Suites"),
    ("Culvers", "Expenses:Food:Restaurants:Culvers"),
    (
        "Great Lakes Eatery & Pub",
        "Expenses:Food:Restaurants:Great-Lakes-Eatery-and-Pub",
    ),
    ("Sherman Service Center", "Expenses:Travel:Fuel:Sherman-Service-Center"),
    ("Kwik Fill", "Expenses:Travel:Fuel:Kwik-Fill"),
    ("Mountain Market", "Expenses:Food:Groceries:Mountain-Market"),
    ("The Woodshed", "Expenses:Food:Restaurants:The-Woodshed"),
    ("Sweetgreen", "Expenses:Food:Restaurants:Sweetgreen"),
    ("Ricky's Flower", "Expenses:Shopping:Plants:Rickys-Flower-Market"),
    ("Kendall Sq Cinema", "Expenses:Entertainment:Movies:Kendall-Sq-Cinema"),
    ("Kendall Square Ecom", "Expenses:Entertainment:Movies:Kendall-Sq-Cinema"),
    ("Kendall Sq Ecom", "Expenses:Entertainment:Movies:Kendall-Sq-Cinema"),
    ("puritan and Company", "Expenses:Food:Restaurants:Puritan-and-Company"),
    ("Uber", "Expenses:Travel:Ride-Sharing:Uber"),
    ("Snack Happy Vending", "Expenses:Food:Vending:Snack-Happy"),
    ("Panjabi Corp", "Expenses:Food:Restaurants:Panjabi-Corp"),
    ("Billy McHale's", "Expenses:Food:Restaurants:Billy-McHales"),
    ("Sea Bad Egg", "Expenses:Food:Restaurants:Seattle-Airport-Bad-Egg"),
    ("Common Man Roadside Nb", "Expenses:Food:Restaurants:Common-Man-Roadside"),
    ("Red's Sandwich Shop", "Expenses:Food:Restaurants:Reds-Sandwich-Shop"),
    ("Butcher Burger", "Expenses:Food:Restaurants:Butcher-Burger"),
    ("Darn Tough", "Expenses:Shopping:Clothing:Darn-Tough"),
    ("Uplift Desk", "Expenses:Shopping:Furniture:Uplift-Desk"),
    ("COURSERA.ORG", "Expenses:Education:Online:Coursera"),
    ("Circle K", "Expenses:Travel:Fuel:Circle-K"),
    ("\*VUE\*Testing Exam", "Expenses:Education:Testing:Pearson-Vue"),
    ("Yosaku", "Expenses:Food:Restaurants:Yosaku"),
    ("Pemberton Farms Mar", "Expenses:Food:Groceries:Pemberton-Farms"),
    ("Caledonia Spirits", "Expenses:Food:Alcohol:Caledonia-Spirits"),
    ("Leport-Royal", "Expenses:Travel:Accommodation:Leport-Royal"),
    ("Strom Spa", "Expenses:Travel:Wellness:Strom-Spa"),
    ("Gesparc \(Monastere\)", "Expenses:Travel:Accommodation:Monastere-Des-Augustins"),
    ("DELTA AIR", "Expenses:Travel:Airfare:Delta"),
    ("Delta", "Expenses:Travel:Airfare:Delta"),
    ("Express Collision Center", "Expenses:Travel:Auto:Express-Collision-Center"),
    ("Snowbird Sports Rent", "Expenses:Travel:Sports:Snowbird-Sports-Rent"),
    ("Sugarbush", "Expenses:Travel:Sports:Sugarbush"),
    ("city of Cambridge", "Expenses:Travel:Auto:Cambridge"),
    ("Cambma Web PMT", "Expenses:Travel:Auto:Cambridge"),
    ("marathon Sports", "Expenses:Shopping:Sports:Marathon-Sports"),
    ("BWH Parking", "Expenses:Travel:Parking:Brigham-and-Womens-Hospital"),
    ("J.G Clay", "Expenses:Shopping:Furniture:J-G-Clay"),
    ("Ikon Pass", "Expenses:Travel:Sports:Ikon-Pass"),
    ("Irving", "Expenses:Travel:Fuel:Irving"),
    ("Oak Creek Events", "Expenses:Travel:Sports:Oak-Creek-Events"),
    ("Citgo", "Expenses:Travel:Fuel:Citgo"),
    ("Harvard Parking Meters", "Expenses:Travel:Parking:Harvard"),
    ("Wawa", "Expenses:Travel:Fuel:Wawa"),
    ("City of Boston Parking", "Expenses:Travel:Parking:Boston"),
    ("A.L. Prime", "Expenses:Travel:Fuel:AL-Prime"),
    ("BUDGET.COM", "Expenses:Travel:Car-Rental:Budget"),
    ("Pmusa", "Expenses:Travel:Fuel:Park-Mobile"),
    ("Chevron", "Expenses:Travel:Fuel:Chevron"),
    ("Lyft", "Expenses:Travel:Ride-Sharing:Lyft"),
    ("Etollbgt", "Expenses:Travel:Tolls:Budget"),
    ("Prestige DRB", "Expenses:Travel:Car-Wash:Prestige"),
    ("Cumberland Farms", "Expenses:Travel:Fuel:Cumberland-Farms"),
    ("Alfredos Italian Kit", "Expenses:Food:Restaurants:Alfredos-Italian-Kitchen"),
    ("Alfredo`s Italian Kit", "Expenses:Food:Restaurants:Alfredos-Italian-Kitchen"),
    ("Coldstone", "Expenses:Food:Ice-Cream:Coldstone"),
    ("Five Guys", "Expenses:Food:Restaurants:Five-Guys"),
    ("Thiccy's Club", "Expenses:Food:Restaurants:Thiccys-Club"),
    ("Trina's Starlight", "Expenses:Food:Restaurants:Trinas-Starlight-Lounge"),
    ("Silver Whisk Bake", "Expenses:Food:Restaurants:Silver-Whisk-Bake"),
    ("Corrib Pub", "Expenses:Food:Restaurants:Corrib-Pub"),
    ("life Alive", "Expenses:Food:Restaurants:Life-Alive"),
    ("Cambridweb PMT", "Expenses:Travel:Auto:Cambridge"),
    ("Cambridge Traffic Web", "Expenses:Travel:Auto:Cambridge"),
    ("Domino's", "Expenses:Food:Restaurants:Dominos"),
    ("Dominos", "Expenses:Food:Restaurants:Dominos"),
    ("Martin Brothers", "Expenses:Food:Groceries:Martin-Brothers"),
    ("All Star Sandwich", "Expenses:Food:Restaurants:All-Star-Sandwich"),
    ("Soup Shack", "Expenses:Food:Restaurants:Soup-Shack"),
    ("The Moth", "Expenses:Entertainment:Nightlife:The-Moth"),
    ("Arts at the Armory", "Expenses:Entertainment:Arts:Arts-at-the-Armory"),
    ("Bloc 11 Cafe", "Expenses:Food:Restaurants:Bloc-11-Cafe"),
    ("Mama Ginas Pizza", "Expenses:Food:Restaurants:Mama-Ginas-Pizza"),
    ("Kftea", "Expenses:Food:Coffee:Kung-Fu-Tea"),
    ("Market Basket", "Expenses:Food:Groceries:Market-Basket"),
    ("Doordash", "Expenses:Food:Delivery:Doordash"),
    ("Gufo", "Expenses:Food:Restaurants:Gufo"),
    ("1369 Coffee House", "Expenses:Food:Coffee:1369-Coffee-House"),
    ("Aeronaut Brewing", "Expenses:Food:Beer:Aeronaut-Brewing"),
    ("Trueleafmarket", "Expenses:Shopping:Plants:True-Leaf-Market"),
    ("Bukowskis", "Expenses:Food:Restaurants:Bukowskis"),
    ("Trillium Brewing", "Expenses:Food:Beer:Trillium-Brewing"),
    ("Steamship", "Expenses:Travel:Ferry:Marthas-Vineyard-Steamship-Concession"),
    ("Pie in the Sky", "Expenses:Food:Restaurants:Pie-in-the-Sky"),
    ("Barcelona", "Expenses:Food:Restaurants:Barcelona"),
    ("Lucky Strike", "Expenses:Entertainment:Nightlife:Lucky-Strike"),
    ("Friendlys", "Expenses:Food:Restaurants:Friendlys"),
    ("Colectivo Coffee", "Expenses:Food:Coffee:Colectivo-Coffee"),
    ("Portillos Hot Dogs", "Expenses:Food:Restaurants:Portillos-Hot-Dogs"),
    ("Beauty Bar", "Expenses:Health:Wellness:Beauty-Bar"),
    ("Ventra", "Expenses:Travel:Public-Transport:Ventra"),
    ("Varietale Bagel", "Expenses:Food:Restaurants:Varietale-Bagel"),
    ("Native Foods", "Expenses:Food:Restaurants:Native-Foods"),
    ("Blue Bottle Coffee", "Expenses:Food:Coffee:Blue-Bottle-Coffee"),
    ("Ramshead Cafeteria", "Expenses:Food:Restaurants:Ramshead-Cafeteria"),
    ("Dumpling Xuan", "Expenses:Food:Restaurants:Dumpling-Xuan"),
    ("Bos-Taco", "Expenses:UNKNOWN"),
    ("Bos-Unio", "Expenses:UNKNOWN"),
    ("Landmark Center Garage", "Expenses:Travel:Parking:Landmark-Center"),
    ("Dave & Busters", "Expenses:Entertainment:Nightlife:Dave-and-Busters"),
    ("Huel", "Expenses:Food:Groceries:Huel"),
    ("Tatte Bakery", "Expenses:Food:Coffee:Tatte-Bakery"),
    ("Nike", "Expenses:Shopping:Clothing:Nike"),
    ("New Republik", "Expenses:Food:Restaurants:New-Republic"),
    ("Broadway Gas", "Expenses:Travel:Fuel:Broadway-Gas"),
    ("Google CLOUD", "Expenses:Cloud-Services:Google-Cloud"),
    ("GOOGLE \*CLOUD", "Expenses:Cloud-Services:Google-Cloud"),
    ("Worthy Burger", "Expenses:Food:Restaurants:Worthy-Burgers"),
    ("Lawson's Finest", "Expenses:Food:Beer:Lawsons-Finest-Liquids"),
    ("Tanjore", "Expenses:Food:Restaurants:Tanjore"),
    ("Bluebik", "Expenses:Travel:Bike-Share:Bluebikes"),
    ("H Mart", "Expenses:Food:Groceries:H-Mart"),
    ("Opus", "Expenses:Food:Restaurants:Opus"),
    ("Satellite", "Expenses:Food:Coffee:Remnant"),
    ("Thelonious Monkfi", "Expenses:Food:Restaurants:Thelonious-Monkfish"),
    ("Temptations Cooli", "Expenses:Food:Coffee:Temptations-Cafe"),
    ("Star Market", "Expenses:Food:Groceries:Star-Market"),
    ("Diesel Cafe", "Expenses:Food:Coffee:Diesel-Cafe"),
    ("jp Licks", "Expenses:Food:Ice-Cream:JP-Licks"),
    ("Saus at Bow Market", "Expenses:Food:Restaurants:Saus-at-Bow-Market"),
    ("Menchies Little", "Expenses:Food:Restaurants:Menchies"),
    ("Menchies Feder", "Expenses:Food:Restaurants:Menchies"),
    ("WALMART", "Expenses:Shopping:Walmart"),
    ("Panera", "Expenses:Food:Restaurants:Panera"),
    ("oleana", "Expenses:Food:Restaurants:Oleana"),
    ("When Pigs Fly", "Expenses:Food:Restaurants:When-Pigs-Fly"),
    ("Mass General Brigham", "Expenses:Health:Medical:Mass-General-Brigham"),
    ("Christina S Ice Cr", "Expenses:Food:Ice-Cream:Christinas-Ice-Cream"),
    ("Vktry Gear", "Expenses:Shopping:Sports:Vktry-Gear"),
    ("Hannaford", "Expenses:Food:Groceries:Hannaford"),
    ("Point Defiance Zoo", "Expenses:Entertainment:Point-Defiance-Zoo"),
    ("marugame Udon", "Expenses:Food:Restaurants:Marugame-Udon"),
    ("Bakery Cafe Usa", "Expenses:Food:Restaurants:Bakery-Cafe-USA"),
    ("Brew Top", "Expenses:Food:Beer:Brew-Top"),
    ("Wm Supercenter", "Expenses:Shopping:Walmart"),
    ("Nayax", "Expenses:UNKNOWN"),
    ("black Bird Caffe", "Expenses:Food:Coffee:Black-Bird-Caffe"),
    ("PDZA", "Expenses:Entertainment:Point-Defiance-Zoo"),
    ("Delaware North", "Expenses:Food:Restaurants:Delaware-North"),
    ("Bagel World", "Expenses:Food:Restaurants:Bagel-World"),
    ("mookies at Mugford", "Expenses:Food:Restaurants:Mookies-at-Mugford"),
    ("Wegmans", "Expenses:Food:Groceries:Wegmans"),
    ("Harbor Burger Shack", "Expenses:Food:Restaurants:Harbor-Burger-Shack"),
    ("Arabica Coffee", "Expenses:Food:Coffee:Arabica-Coffee"),
    ("Eagle S Deli", "Expenses:Food:Restaurants:Eagles-Deli"),
    ("the Daily Brew", "Expenses:Food:Coffee:The-Daily-Brew"),
    ("Homegoods", "Expenses:Shopping:Homegoods"),
    ("lobster Trap", "Expenses:Food:Restaurants:Lobster-Trap"),
    ("Genki Ya", "Expenses:Food:Restaurants:Genki-Ya"),
    ("Charlton, MA - Tre", "Expenses:Food:Beer:Tree-House-Brewing"),
    ("Cambridge", "Expenses:UNKNOWN"),
    ("Dakzen", "Expenses:Food:Restaurants:Dakzen"),
    ("Oletogo", "Expenses:Food:Restaurants:Ole"),
    ("7-Eleven", "Expenses:Travel:Fuel:7-Eleven"),
    ("sumo", "Expenses:Food:Restaurants:Sumo-Asian-Bistro"),
    ("Regal Cinemas", "Expenses:Entertainment:Movies:Regal-Cinemas"),
    ("Fredericksburg 14", "Expenses:Entertainment:Movies:Regal-Cinemas"),
    ("Sweetfrog", "Expenses:Food:Restaurants:Sweetfrog"),
    ("Poke Mian", "Expenses:Food:Restaurants:Poke-Mian"),
    ("Crave & Co", "Expenses:Food:Restaurants:Crave-and-Co"),
    ("The Good Life Market", "Expenses:Food:Groceries:The-Good-Life-Market"),
    ("The Crooked Mile Cafe", "Expenses:Food:Restaurants:The-Crooked-Mile-Cafe"),
    ("Butternut Bakeh", "Expenses:Food:Restaurants:Butternut-Bakehouse"),
    ("3 Little Figs", "Expenses:Food:Restaurants:3-Little-Figs"),
    ("boston Burger Co", "Expenses:Food:Restaurants:Boston-Burger-Company"),
    ("long Island Bagel", "Expenses:Food:Restaurants:Long-Island-Bagel"),
    ("captain Lawrence", "Expenses:Food:Beer:Captain-Lawrence-Brewing-Company"),
    ("Delucas Market", "Expenses:Food:Restaurants:Delucas-Market"),
    ("730 Tavern", "Expenses:Food:Restaurants:730-Tavern"),
    ("ZOLA", "Expenses:Shopping:Weddings:Zola"),
    ("posto", "Expenses:Food:Restaurants:Posto"),
    ("Ono Pokebar", "Expenses:Food:Restaurants:Ono-Pokebar"),
    ("Crescent Ridge Dairy", "Expenses:Food:Groceries:Crescent-Ridge-Dairy"),
    ("Boston Glory", "Expenses:Entertainment:Sports:Boston-Glory"),
    ("uncharted Tea", "Expenses:Food:Coffee:Uncharted-Tea-and-Coffee"),
    ("Hogan Bro", "Expenses:Food:Restaurants:Hogan-Brothers"),
    ("Taco Bell", "Expenses:Food:Restaurants:Taco-Bell"),
    ("The Blast", "Expenses:Food:Desserts:The-Blast"),
    ("Sayles Cafe", "Expenses:Food:Restaurants:Sayles-Cafe"),
    ("Little Joy Coffee", "Expenses:Food:Coffee:Little-Joy-Coffee"),
    ("MSP Airp Peoples Organ", "Expenses:Food:Restaurants:Peoples-Organic"),
    ("Northfield Liquor Stor", "Expenses:Food:Alcohol:Northfield-Liquors"),
    ("black Sheep Bagel", "Expenses:Food:Restaurants:Black-Sheep-Bagel"),
    ("daves Fresh Pasta", "Expenses:Food:Groceries:Daves-Fresh-Pasta"),
    ("dirty Water Dough", "Expenses:Food:Coffee:Dirty-Water-Doughnuts"),
    ("Cafe Zing", "Expenses:Food:Restaurants:Cafe-Zing"),
    ("Star Osco", "Expenses:Food:Groceries:Star-Osco"),
    ("Union Square Donut", "Expenses:Food:Restaurants:Union-Square-Donuts"),
    ("Masala", "Expenses:Food:Restaurants:Masala"),
    ("the Helmand", "Expenses:Food:Restaurants:The-Helmand"),
    ("bakey Kendall Squa", "Expenses:Food:Restaurants:Bakey"),
    ("Kendall Square 231", "Expenses:UNKNOWN"),
    ("Teele Square Liquor", "Expenses:Food:Alcohol:Teele-Square-Liquor"),
    ("dali Restaurant", "Expenses:Food:Restaurants:Dali"),
    ("Fsdiscraftdiscs", "Expenses:Shopping:Sports:Frisbee-Disc-Crafts"),
    ("Turing Tavern", "Expenses:Food:Restaurants:Turing-Tavern"),
    ("Ls City Liquors", "Expenses:Food:Alcohol:LS-City-Liquors"),
    ("Siam Ginger", "Expenses:Food:Restaurants:Siam-Ginger"),
    ("Brick & Mortar", "Expenses:Food:Restaurants:Brick-and-Mortar"),
    ("Roundhouse Rest", "Expenses:Food:Restaurants:Roundhouse-Restaurant"),
    ("Moonbeam Rest Solitude", "Expenses:Food:Restaurants:Moonbeam-Restaurant"),
    ("Summit Restaurant", "Expenses:Food:Restaurants:Summit-Restaurant"),
    ("Baked & Brewed", "Expenses:Food:Coffee:Baked-and-Brewed"),
    ("A Bar Name Sue", "Expenses:Food:Restaurants:A-Bar-Named-Sue"),
    ("Silver Lake Rest", "Expenses:Food:Restaurants:Silver-Lake-Restaurant"),
    ("Deer Valley Etc", "Expenses:Travel:Sports:Deer-Valley"),
    ("Delta Center Arena", "Expenses:Entertainment:Sports:Utah-Jazz"),
    ("Alta Ski Area F&b", "Expenses:Travel:Sports:Alta"),
    ("Goldminers Restaurant", "Expenses:Food:Restaurants:Goldminers-Restaurant"),
    ("Alta Java", "Expenses:Food:Coffee:Alta-Java"),
    ("Tram Car Pizza", "Expenses:Food:Restaurants:Tram-Car-Pizza"),
    ("Brighton Resort", "Expenses:Travel:Sports:Brighton-Resort"),
    ("Jimmy Johns", "Expenses:Food:Restaurants:Jimmy-Johns"),
    ("The Coolidge Corner Th", "Expenses:Entertainment:Movies:Coolidge-Corner-Theatre"),
    ("Hot Chix Boston", "Expenses:Food:Restaurants:Hot-Chix-Boston"),
    ("Google Play", "Expenses:Cloud-Services:Google-Play"),
    ("APPLE.COM/US", "Expenses:Cloud-Services:Apple"),
    ("Exotic Wine & Spirits", "Expenses:Food:Alcohol:Exotic-Wine-and-Spirits"),
    ("Yellow - Georgeto", "Expenses:Food:Restaurants:Yellow"),
    ("Septa", "Expenses:Travel:Public-Transport:SEPTA"),
    ("New Deck Tavern", "Expenses:Food:Restaurants:New-Deck-Tavern"),
    ("Waffle House", "Expenses:Food:Restaurants:Waffle-House"),
    ("Domoishi", "Expenses:Food:Restaurants:Domoishi"),
    ("Waikiki", "Expenses:Food:Restaurants:Waikiki"),
    ("Parkmobile", "Expenses:Travel:Parking:Park-Mobile"),
    ("Passage to India", "Expenses:Food:Restaurants:Passage-to-India"),
    ("BACKCOUNTRY.COM", "Expenses:Shopping:Sports:Backcountry"),
    ("Chilacates", "Expenses:Food:Restaurants:Chilacates"),
    ("Portico Brewing", "Expenses:Food:Beer:Portico-Brewing"),
    ("Ba@carleton", "Expenses:Education:Carleton-College"),
    ("Toscanini's", "Expenses:Food:Ice-Cream:Toscaninis"),
    ("Kantipurcafe", "Expenses:Food:Restaurants:Kantipur-Cafe"),
    ("Kantipur Cafe", "Expenses:Food:Restaurants:Kantipur-Cafe"),
    ("Chez Rafiki", "Expenses:Food:Restaurants:Chez-Rafiki"),
    ("Fresh Pond Beer", "Expenses:Food:Beer:Fresh-Pond-Beer"),
    ("Idemia Tsa Precheck", "Expenses:Travel:Testing:Idemia-TSA-Precheck"),
    ("Stop & Shop", "Expenses:Food:Groceries:Stop-and-Shop"),
    ("Lisas Family Pizz", "Expenses:Food:Restaurants:Lisas-Family-Pizza"),
    ("Frosty Harbor", "Expenses:Food:Ice-Cream:Frosty-Harbor"),
    ("Thai Tree", "Expenses:Food:Restaurants:Thai-Tree"),
    ("Shake Shack", "Expenses:Food:Restaurants:Shake-Shack"),
    ("Old Town News", "Expenses:Shopping:Books:Old-Town-News"),
    ("Sea Ballard Brewhall", "Expenses:Food:Beer:Ballard-Brewhall"),
    ("Teele Square Market", "Expenses:Food:Groceries:Teele-Square-Market"),
    ("JoesNewBalanceOutlet", "Expenses:Shopping:Clothing:Joes-New-Balance-Outlet"),
    ("Curio Coffee", "Expenses:Food:Coffee:Curio-Coffee"),
    ("Playa Bowls", "Expenses:Food:Restaurants:Playa-Bowls"),
    ("Gross Confection", "Expenses:Food:Desserts:Gross-Confection-Bar"),
    ("Tiktok Shop", "Expenses:Shopping:Online:TikTok-Shop"),
    ("oak Bistro", "Expenses:Food:Restaurants:Oak-Bistro"),
    ("Anoche", "Expenses:Food:Restaurants:Anoche"),
    ("The Cookie Monstah", "Expenses:Food:Desserts:The-Cookie-Monstah"),
    ("Kings Back Bay", "Expenses:Entertainment:Bowling:Kings-Back-Bay"),
    ("Third Time Ice Cr", "Expenses:Food:Ice-Cream:Third-Time-Ice-Cream"),
    ("Osawa Bistro", "Expenses:Food:Restaurants:Osawa-Bistro"),
    ("Petra Mediterranean", "Expenses:Food:Restaurants:Petra-Mediterranean"),
    ("CVS/Pharmacy", "Expenses:Health:Pharmacy:CVS"),
    ("Family Market", "Expenses:Food:Groceries:Family-Market"),
    ("Mimi's Chuka Dine", "Expenses:Food:Restaurants:Mimis-Chuka-Diner"),
    ("Kaze Shabu Shabu", "Expenses:Food:Restaurants:Kaze-Shabu-Shabu"),
    ("Le Lapin Saute", "Expenses:Food:Restaurants:Le-Lapin-Saute"),
    ("Sapristi", "Expenses:Food:Restaurants:Sapristi"),
    ("Boutique Alliage", "Expenses:Shopping:Art:Boutique-Alliage"),
    ("Les Trouvailles De Jul", "Expenses:Shopping:Art:Les-Trouvailles-De-Julie"),
    ("TEKNOTIP.CA", "Expenses:Shopping:Teknotip"),
    ("Restaurant Asia", "Expenses:Food:Restaurants:Restaurant-Asia"),
    ("La Maison Smith", "Expenses:Food:Coffee:La-Maison-Smith"),
    ("21st Amendment", "Expenses:Food:Beer:21st-Amendment"),
    ("Gypsy Cafe", "Expenses:Food:Coffee:Gypsy-Cafe"),
    ("Vertigo Vinyl", "Expenses:Shopping:Music:Vertigo-Vinyl"),
    ("sarma Restaurant", "Expenses:Food:Restaurants:Sarma"),
    ("Davids", "Expenses:Food:Restaurants:Davids"),
    ("Snowbird", "Expenses:Travel:Sports:Snowbird"),
    ("Slope Side Cafe", "Expenses:Food:Restaurants:Slope-Side-Cafe"),
    ("Orale Mexican Grill", "Expenses:Food:Restaurants:Orale-Mexican-Grill"),
    (
        "Sweet Lake Biscuits",
        "Expenses:Food:Restaurants:Sweet-Lake-Biscuits-and-Limeade",
    ),
    ("spoke Wine Bar", "Expenses:Food:Restaurants:Spoke-Wine-Bar"),
    ("Mr. Crepe", "Expenses:Food:Restaurants:Mr-Crepe"),
    ("Mehuron's Supermarke", "Expenses:Food:Groceries:Mehurons-Supermarket"),
    ("three Penny Taproo", "Expenses:Food:Restaurants:Three-Penny-Taproom"),
    ("davis Square Donut", "Expenses:Food:Restaurants:Davis-Square-Donuts"),
    ("Boston Pub MKT West", "Expenses:Food:Restaurants:Boston-Pub-Market-West"),
    ("Slopeside Grill", "Expenses:Food:Restaurants:Slopeside-Grill"),
    ("sugar & Spice", "Expenses:Food:Desserts:Sugar-and-Spice"),
    ("Brewery", "Expenses:Food:Beer:UNKNOWN"),
    ("Taqueria Mariana", "Expenses:Food:Restaurants:Taqueria-Mariana"),
    ("Nine Bar Espresso", "Expenses:Food:Coffee:Nine-Bar-Espresso"),
]

checking_account_patterns = [
    ("Mock Init Balance", "Income:Opening-Balances"),
    ("VENMO", "Assets:Checking:Venmo"),
    ("COSTCO", "Expenses:Shopping:Costco"),
    ("Deposit from 360 Performance Savings", "Assets:Savings:CapitalOne"),
    ("Monthly Interest Paid", "Income:Interest:CapitalOne"),
    ("PASSPORT PKG", "Expenses:Travel:Passport-Parking"),
    ("CITY OF CAMBRIDG TRAFFICWEB", "Expenses:Travel:Parking:Cambridge"),
    ("FEE CAMBRIDGE WEB", "Expenses:Travel:Parking:Cambridge"),
    ("GOODWILL", "Expenses:Shopping:Goodwill"),
    ("TOWN OF MARBLEHE", "Expenses:Travel:Auto:Marblehead"),
    ("ALLTOWN LOND", "Expenses:Travel:Fuel:Alltown-Londonderry"),
    ("CITY OF CAMBRIDGE CHARLOTTE NC", "Expenses:Travel:Parking:Cambridge"),
    ("SPLITWISE PAYMENT", "Expenses:Travel:Splitwise"),
    ("TOPSCORE", "Expenses:Sports:Frisbee:Topscore"),
    ("CVS/PHARMACY", "Expenses:Health:Pharmacy:CVS"),
    ("WAWA", "Expenses:Travel:Fuel:Wawa"),
    ("ATM Withdrawal", "Expenses:UNKNOWN"),
    ("Givedirectly", "Expenses:Charity:GiveDirectly"),
    ("UNIVERSITY OF PE", "Income:Expenses:UPenn"),
    ("O'BRIEN'S GENERA", "Expenses:Shopping:Groceries:OBriens-General-Store"),
    ("COINBASE", "Expenses:Investments:Crypto:Coinbase"),
    ("JIFFY MART", "Expenses:Travel:Fuel:Jiffy-Mart"),
    ("Check", "Expenses:Rent"),
    ("BROADWAY GAS", "Expenses:Travel:Fuel:Broadway-Gas"),
    ("SHELL OIL", "Expenses:Travel:Fuel:Shell"),
    ("PMUSA", "Expenses:Travel:Parking:Park-Mobile"),
]

savings_account_patterns = [
    ("Mock Init Balance", "Income:Opening-Balances"),
    ("Withdrawal to 360 Checking", "Assets:Checking:CapitalOne"),
    ("TRUSTEES OF UNIV PAYROLL", "Income:Salary:UPenn"),
    ("Monthly Interest Paid", "Income:Interest:CapitalOne"),
    ("CAPITAL ONE CRCARDPMT", "Liabilities:Credit-Cards:CapitalOne"),
    ("VANGUARD BUY", "Assets:Investments:Vanguard:Roth-IRA:Cash"),
    ("IRS USATAXPYMT", "Income:Taxes:Federal"),
    ("COMM OF MASS EFT", "Income:Taxes:MA"),
    ("MA Tax Refund", "Income:Taxes:MA"),
    ("COMMWLTHOFPA", "Income:Taxes:PA"),
    ("COMM OF PA PA REFUND", "Income:Taxes:PA"),
    ("Granny", "Income:Gift:Granny-And-Grampsy"),
    ("Grandma", "Income:Gift:Grandma-And-Grandpa"),
    ("Grandpa", "Income:Gift:Grandma-And-Grandpa"),
    ("PAYPAL", "Expenses:Shopping:PayPal"),
    ("EVERSOURCE WEB_PAY", "Expenses:Utilities:Eversource"),
    ("COMCAST-XFINITY", "Expenses:Utilities:Internet:Comcast-Xfinity"),
]

CONFIG = [
    CapitalOneCreditCardImporter(
        "Liabilities:Credit-Cards:CapitalOne:Quicksilver",
        currency="USD",
        lastfour="9963",
        account_patterns=account_patterns
        + [("Cash Auto Redemption", "Income:Rewards:CapitalOne:Quicksilver")],
    ),
    CapitalOneCreditCardImporter(
        "Liabilities:Credit-Cards:CapitalOne:Quicksilver",
        currency="USD",
        lastfour="7742",
        account_patterns=account_patterns
        + [("Cash Auto Redemption", "Income:Rewards:CapitalOne:Quicksilver")],
    ),
    CapitalOneCreditCardImporter(
        "Liabilities:Credit-Cards:CapitalOne:SavorOne",
        currency="USD",
        lastfour="3392",
        account_patterns=account_patterns
        + [("Cash Auto Redemption", "Income:Rewards:CapitalOne:SavorOne")],
    ),
    CapitalOneCreditCardImporter(
        "Liabilities:Credit-Cards:CapitalOne:VentureX",
        currency="USD",
        lastfour="6618",
        account_patterns=account_patterns,
    ),
    CapitalOneDepositAccountImporter(
        "Assets:Checking:CapitalOne",
        account_no="7746",
        currency="USD",
        account_patterns=checking_account_patterns,
    ),
    CapitalOneDepositAccountImporter(
        "Assets:Savings:CapitalOne",
        account_no="7830",
        currency="USD",
        account_patterns=savings_account_patterns,
    ),
    VenmoImporter(
        "Assets:Checking:Venmo",
        currency="USD",
    ),
    FidelityImporter(
        "Assets:Investments:Fidelity",
        currency="USD",
        account_nos={
            "X94909428": "Assets:Investments:Fidelity:Brokerage",
            "Y81595674": "Assets:Investments:Fidelity:Large-Cap",
        },
        cusip_map={
            "03662Q105": 'ANSS',
            "254709108": 'DFS',
            "42809H107": 'HES',
            "931427108": 'WBA',
        },
    ),
    VanguardImporter(
        "Assets:Investments:Vanguard",
        currency="USD",
        account_nos={
            "45886834": "Assets:Investments:Vanguard:Roth-IRA",
            "74065422": "Assets:Investments:Vanguard:Brokerage",
        },
    ),
    #HealthEquityImporter(
    #    "Assets:Investments:HealthEquity:HSA",
    #    currency="USD",
    #)
]
